Add solution for 'Serialization' module home task
cezary-kania/EPAM-dotnet-Basics pull request #10
Opened 2023-07-07 20:46 UTC by cezary-kania

2023-07-17 08:59 UTC, KirylPrykhodzka requested changes

2023-07-17 08:59 UTC, KirylPrykhodzka commented on Module-10/Task1.JSONSerialization/Program.cs
> +        new() { EmployeeName = "SD-1 Employee 1" },
you don't need to fix this, but in general it is better to use more real-world-like data to make your code easier to understand (especially when it's test code).
So a better EmployeeName would be "Jack Daniels" or "Frodo Baggins" or whatever other name you can come up with

2023-07-17 08:59 UTC, KirylPrykhodzka commented on Module-10/Task1.JSONSerialization/Department.cs
> +    [JsonPropertyName("Name")]
Generally serialized property names start with lowercase ("name" instead of "Name")

2023-07-17 08:59 UTC, KirylPrykhodzka commented on Module-10/Task3/Department.cs
> +    public Department DeepClone()
1. Deep cloning should be type-independent, and Employee type has to support it as well according to the task. Think of a way to achieve this without code duplication
2. Using BinaryFormatter here is not safe because is requires `[Serializable]` attribute on each serialized property (including nested ones). You can use Xml or Json serialization instead

2023-07-17 08:59 UTC, KirylPrykhodzka commented on Module-10/Task3/Program.cs
> +Console.WriteLine(clonedDepartment);
the best way to prove that your deep cloning works is by writing a simple unit test which will create an object, deep clone it, and then compare all the properties by value and by reference (values should be identical and references should be different)

2023-07-18 18:03 UTC, cezary-kania commented on Module-10/Task3/Program.cs
> +Console.WriteLine(clonedDepartment);
I added new test. Please check.

2023-07-18 18:03 UTC, cezary-kania commented on Module-10/Task3/Department.cs
> +    public Department DeepClone()
Done.

2023-07-18 18:04 UTC, cezary-kania commented on Module-10/Task1.JSONSerialization/Department.cs
> +    [JsonPropertyName("Name")]
Done.

2023-07-19 08:42 UTC, KirylPrykhodzka approved these changes

2023-07-20 18:51 UTC, merged